version: "3.9"

services:
  # 🧠 AI Dialer Backend
  ai_dialer:
    build: .
    container_name: ai_dialer_server
    command: cd server && npm start
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - asterisk
    networks:
      - ai-dialer-net
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
      - ./audio-cache:/usr/src/app/audio-cache
    restart: always

  # ☎️ Asterisk PBX Server
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    networks:
      - ai-dialer-net
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8088:8088"
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-logs:/var/log/asterisk
      - ./audio-cache:/var/lib/asterisk/sounds/custom
    environment:
      - ARI_PASSWORD=ai-dialer-password
    restart: always

  # 🗄️ PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_dialer
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ai-dialer-net

  # ⚡ Redis Cache
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ai-dialer-net
    restart: always

networks:
  ai-dialer-net:
    driver: bridge

volumes:
  pg_data:
