services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-dialer-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai_dialer_prod}
      POSTGRES_USER: ${POSTGRES_USER:-ai_dialer_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ai_dialer_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-dialer-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ai-dialer-redis
    restart: always
    command: redis-server ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli ${REDIS_PASSWORD:+-a $REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-dialer-network

  # Asterisk VoIP Server
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    container_name: ai-dialer-asterisk
    restart: always
    environment:
      ARI_USERNAME: ${ARI_USERNAME:-ai-dialer}
      ARI_PASSWORD: ${ARI_PASSWORD}
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-logs:/var/log/asterisk
      - asterisk_sounds:/var/lib/asterisk/sounds
    ports:
      - "8088:8088"
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
    networks:
      - ai-dialer-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-dialer-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Database Configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-ai_dialer_prod}
      - POSTGRES_USER=${POSTGRES_USER:-ai_dialer_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-ai_dialer_prod}
      - DB_USER=${POSTGRES_USER:-ai_dialer_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # Asterisk Configuration
      - ASTERISK_HOST=asterisk
      - ASTERISK_ARI_PORT=8088
      - ARI_URL=http://asterisk:8088/ari
      - ARI_USERNAME=${ARI_USERNAME:-ai-dialer}
      - ARI_PASSWORD=${ARI_PASSWORD}
      # JWT & Session
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - JWT_EXPIRES_IN=7d
      - SESSION_SECRET=${SESSION_SECRET:-change-this-session-secret}
      # CORS Configuration (use CLIENT_URL env var or default to localhost)
      - CORS_ORIGIN=${CLIENT_URL:-http://localhost:3001}
      - API_URL=${API_URL:-http://localhost:3000}
      # Application Settings
      - LOG_LEVEL=info
      - MAX_CONCURRENT_CALLS=10
      - VOICE_STACK=self_hosted
      - TTS_ENGINE=espeak
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELNYX_API_KEY=${TELNYX_API_KEY}
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
      - ./audio-cache:/app/audio-cache
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-dialer-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      asterisk:
        condition: service_started

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /api/v1
        REACT_APP_WS_URL: /ws
    container_name: ai-dialer-frontend
    restart: always
    ports:
      - "3001:80"
    networks:
      - ai-dialer-network
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  asterisk_sounds:
    driver: local

networks:
  ai-dialer-network:
    driver: bridge
