services:
  # 🧠 AI Dialer Backend
  ai_dialer:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: ai_dialer_server
    ports:
      - "3000:3000"
    environment:
      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ai_dialer
      - DB_USER=postgres
      - DB_PASSWORD=postgres

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      # API
      - NODE_ENV=development
      - DOCKER_ENV=true
      - PORT=3000
      - API_URL=http://localhost:3000/api/v1
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h

      # Asterisk ARI
      - ARI_URL=http://asterisk:8088/ari
      - ARI_USERNAME=ai-dialer
      - ARI_PASSWORD=ai-dialer-password

      # Telnyx Configuration (for outbound calls)
      - TELNYX_USERNAME=info@pitchnhire.com
      - TELNYX_DOMAIN=sip.telnyx.com
      - TELNYX_PASSWORD=DxZU$m4#GuFhRTp
      - TELNYX_SIP_URI=sip:info@pitchnhire.com@sip.telnyx.com
      - TELNYX_IP_RANGE=66.109.0.0/16
      - TELNYX_CALLER_ID=+12025550123
      - TELNYX_DID=+12025550123
      - TELNYX_TIMEOUT=30

      # Voice Stack
      - VOICE_STACK=self_hosted

      # CORS - Allow both local frontend and Docker frontend
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000,http://frontend:3001

      # Logging
      - LOG_LEVEL=info
      - DEBUG=ai-dialer:*
      - ENABLE_DEBUG_LOGS=true

      # Features
      - ENABLE_EMOTION_DETECTION=true
      - ENABLE_VOICE_ANALYTICS=true
      - ENABLE_CALL_RECORDING=true
      - ENABLE_REAL_TIME_MONITORING=true
      - ENABLE_AI_CONVERSATION=true

      # TTS - Using eSpeak for cost optimization
      - TTS_ENGINE=espeak
      - TTS_LANGUAGE=en-US
      - TTS_VOICE=en-us
      - TTS_SPEED=150
      - TTS_PITCH=50
      - TTS_VOLUME=100
      - TTS_CACHE_ENABLED=true
      - TTS_CACHE_TTL=3600
      - TTS_CACHE_MAX_SIZE=1000

      # Call Settings - Optimized for cost
      - DEFAULT_CALL_TIMEOUT=30
      - MAX_CALL_DURATION=180
      - MAX_CONCURRENT_CALLS=10

      # Rate Limiting - More generous for development
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000

      # Health Check
      - HEALTH_CHECK_INTERVAL=30000
      - HEALTH_CHECK_TIMEOUT=5000

      # Database Pool
      - DB_POOL_MIN=2
      - DB_POOL_MAX=10
      - DB_POOL_IDLE_TIMEOUT=30000
    depends_on:
      - postgres
      - redis
      - asterisk
    networks:
      - ai-dialer-net
    volumes:
      - ./server:/usr/src/app
      - ./logs:/usr/src/app/logs
      - ./audio-cache:/usr/src/app/audio-cache
      - /usr/src/app/node_modules
    restart: always

  # 🌐 AI Dialer Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: ai_dialer_frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api/v1
      - REACT_APP_WS_URL=ws://ai_dialer:3000
      - REACT_APP_API_BASE_URL=http://localhost:3000
    depends_on:
      - ai_dialer
    networks:
      - ai-dialer-net
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always

  # ☎️ Asterisk PBX Server
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    networks:
      - ai-dialer-net
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8088:8088"
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-logs:/var/log/asterisk
      - ./audio-cache:/var/lib/asterisk/sounds/custom
      - ./server/asterisk:/var/lib/asterisk/agi-bin
    environment:
      - ARI_PASSWORD=ai-dialer-password
    restart: always

  # 🗄️ PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_dialer
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ai-dialer-net

  # ⚡ Redis Cache
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ai-dialer-net
    restart: always

networks:
  ai-dialer-net:
    driver: bridge
volumes:
  pg_data:
