version: '3.8'

services:
  # Asterisk with ARI enabled (you will need a prebuilt image or Dockerfile)
  asterisk:
    image: andrius/asterisk
    container_name: ai-dialer-asterisk
    volumes:
      - ./asterisk/pjsip.conf:/etc/asterisk/pjsip.conf:ro
      - ./asterisk/extensions.conf:/etc/asterisk/extensions.conf:ro
      - ./asterisk/http.conf:/etc/asterisk/http.conf:ro
      - ./asterisk/ari.conf:/etc/asterisk/ari.conf:ro
    environment:
      - ARI_USER=${ARI_USER:-ari_user}
      - ARI_PASS=${ARI_PASS:-ari_password}
    ports:
      - "5060:5060/udp"   # SIP
      - "8088:8088"       # ARI HTTP
    networks:
      - dialer

  asr:
    image: ghcr.io/guillaumekln/faster-whisper-server:latest
    container_name: ai-dialer-asr
    command: ["--model", "small", "--compute_type", "int8"]
    ports:
      - "8001:8000"
    networks:
      - dialer

  llm:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: ai-dialer-llm
    command: ["-m", "/models/7b-q4.gguf", "-c", "2048", "-ngl", "0"]
    volumes:
      - ./models:/models
    ports:
      - "8002:8080"
    networks:
      - dialer

  tts:
    image: ghcr.io/coqui-ai/xtts-server:latest
    container_name: ai-dialer-tts
    environment:
      - COQUI_TOS_AGREED=1
    ports:
      - "8003:80"
    networks:
      - dialer

networks:
  dialer:
    driver: bridge

